services:
  postgres:
    image: postgres:17.9-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - "127.0.0.1:${APP_PORT}:${APP_PORT}"
    env_file:
      - .env.prod
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-data:
