import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Brackets, In, Repository } from 'typeorm';
import { HelpCenterEntity } from '../entities/help-center.entity';
import { HelpCenter } from '../../../../domain/help-center';
import { HelpCenterRepository } from '../../help-center.repository';
import { HelpCenterMapper } from '../mappers/help-center.mapper';
import { NullableType } from '../../../../../utils/types/nullable.type';
import { IPaginationOptions } from '../../../../../utils/types/pagination-options';
import {
  FilterHelpCenterDto,
  SortHelpCenterDto,
} from '../../../../dto/find-all-help-center.dto';

/**
 * Rank for ordering help-center articles by category in a fixed business
 * order: Getting Started -> Plans & Payments -> Troubleshooting -> FAQ.
 *
 * Uses LOWER + LIKE so it matches both English ("Getting Started",
 * "getting_started") and Vietnamese ("Bắt đầu", "Gói & Thanh toán", ...)
 * variants without needing exact equality.
 *
 * Note: column reference uses the quoted TypeORM alias `"helpCenter"` so
 * Postgres preserves the camelCase alias generated by the query builder.
 */
const HELP_CENTER_CATEGORY_RANK_SQL = `(CASE
  WHEN LOWER("helpCenter"."category") LIKE '%getting%'
    OR LOWER("helpCenter"."category") LIKE '%bắt đầu%'
    OR LOWER("helpCenter"."category") LIKE '%bat dau%'
    OR LOWER("helpCenter"."category") LIKE '%hướng dẫn%'
    OR LOWER("helpCenter"."category") LIKE '%huong dan%'
    THEN 1
  WHEN LOWER("helpCenter"."category") LIKE '%plan%'
    OR LOWER("helpCenter"."category") LIKE '%payment%'
    OR LOWER("helpCenter"."category") LIKE '%gói%'
    OR LOWER("helpCenter"."category") LIKE '%goi%'
    OR LOWER("helpCenter"."category") LIKE '%thanh toán%'
    OR LOWER("helpCenter"."category") LIKE '%thanh toan%'
    THEN 2
  WHEN LOWER("helpCenter"."category") LIKE '%trouble%'
    OR LOWER("helpCenter"."category") LIKE '%khắc phục%'
    OR LOWER("helpCenter"."category") LIKE '%khac phuc%'
    OR LOWER("helpCenter"."category") LIKE '%sự cố%'
    OR LOWER("helpCenter"."category") LIKE '%su co%'
    THEN 3
  WHEN LOWER("helpCenter"."category") LIKE '%faq%'
    OR LOWER("helpCenter"."category") LIKE '%câu hỏi%'
    OR LOWER("helpCenter"."category") LIKE '%cau hoi%'
    THEN 4
  ELSE 999
END)`;

@Injectable()
export class HelpCenterRelationalRepository implements HelpCenterRepository {
  constructor(
    @InjectRepository(HelpCenterEntity)
    private readonly repo: Repository<HelpCenterEntity>,
  ) {}

  async create(
    data: Omit<HelpCenter, 'id' | 'createdAt' | 'updatedAt'>,
  ): Promise<HelpCenter> {
    const newEntity = await this.repo.save(
      this.repo.create(HelpCenterMapper.toPersistence(data as HelpCenter)),
    );
    return HelpCenterMapper.toDomain(newEntity);
  }

  async findAllWithPagination({
    filterOptions,
    sortOptions,
    paginationOptions,
  }: {
    filterOptions?: FilterHelpCenterDto | null;
    sortOptions?: SortHelpCenterDto[] | null;
    paginationOptions: IPaginationOptions;
  }): Promise<[HelpCenter[], number]> {
    const qb = this.repo.createQueryBuilder('helpCenter');

    if (filterOptions?.language) {
      qb.andWhere('helpCenter.language = :language', {
        language: filterOptions.language,
      });
    }
    if (filterOptions?.category) {
      qb.andWhere('helpCenter.category = :category', {
        category: filterOptions.category,
      });
    }
    if (filterOptions?.parent) {
      qb.andWhere('helpCenter.parent = :parent', {
        parent: filterOptions.parent,
      });
    }
    if (typeof filterOptions?.isPopular === 'boolean') {
      qb.andWhere('helpCenter."isPopular" = :isPopular', {
        isPopular: filterOptions.isPopular,
      });
    }
    if (typeof filterOptions?.isPublished === 'boolean') {
      qb.andWhere('helpCenter."isPublished" = :isPublished', {
        isPublished: filterOptions.isPublished,
      });
    }
    if (filterOptions?.search) {
      qb.andWhere(
        new Brackets((sub) => {
          sub
            .where('helpCenter.title ILIKE :search', {
              search: `%${filterOptions.search}%`,
            })
            .orWhere('helpCenter.category ILIKE :search', {
              search: `%${filterOptions.search}%`,
            })
            .orWhere('helpCenter.parent ILIKE :search', {
              search: `%${filterOptions.search}%`,
            });
        }),
      );
    }

    if (sortOptions?.length) {
      sortOptions.forEach((sort) => {
        qb.addOrderBy(
          `helpCenter.${sort.orderBy}`,
          sort.order as 'ASC' | 'DESC',
        );
      });
    } else {
      qb.orderBy(HELP_CENTER_CATEGORY_RANK_SQL, 'ASC');
      qb.addOrderBy('helpCenter.order', 'ASC');
      qb.addOrderBy('helpCenter.createdAt', 'DESC');
      qb.addOrderBy('helpCenter.id', 'ASC');
    }

    qb.skip((paginationOptions.page - 1) * paginationOptions.limit);
    qb.take(paginationOptions.limit);

    const [entities, count] = await qb.getManyAndCount();
    return [entities.map(HelpCenterMapper.toDomain), count];
  }

  async searchForUser({
    keyword,
    language,
    paginationOptions,
  }: {
    keyword: string;
    language?: string;
    paginationOptions: IPaginationOptions;
  }): Promise<[HelpCenter[], number]> {
    const qb = this.repo.createQueryBuilder('helpCenter');

    qb.andWhere('helpCenter."isPublished" = :isPublished', {
      isPublished: true,
    });

    if (language) {
      qb.andWhere('helpCenter.language = :language', { language });
    }

    qb.andWhere(
      new Brackets((sub) => {
        sub
          .where('helpCenter.title ILIKE :search', {
            search: `%${keyword}%`,
          })
          .orWhere('helpCenter.content ILIKE :search', {
            search: `%${keyword}%`,
          });
      }),
    );

    qb.orderBy('helpCenter."isPopular"', 'DESC');
    qb.addOrderBy(HELP_CENTER_CATEGORY_RANK_SQL, 'ASC');
    qb.addOrderBy('helpCenter.order', 'ASC');
    qb.addOrderBy('helpCenter.createdAt', 'DESC');
    qb.addOrderBy('helpCenter.id', 'ASC');

    qb.skip((paginationOptions.page - 1) * paginationOptions.limit);
    qb.take(paginationOptions.limit);

    const [entities, count] = await qb.getManyAndCount();
    return [entities.map(HelpCenterMapper.toDomain), count];
  }

  async findById(id: HelpCenter['id']): Promise<NullableType<HelpCenter>> {
    const entity = await this.repo.findOne({ where: { id } });
    return entity ? HelpCenterMapper.toDomain(entity) : null;
  }

  async findBySlug(slug: string): Promise<NullableType<HelpCenter>> {
    const entity = await this.repo.findOne({ where: { slug } });
    return entity ? HelpCenterMapper.toDomain(entity) : null;
  }

  async findByIds(ids: HelpCenter['id'][]): Promise<HelpCenter[]> {
    const entities = await this.repo.find({ where: { id: In(ids) } });
    return entities.map(HelpCenterMapper.toDomain);
  }

  async update(
    id: HelpCenter['id'],
    payload: Partial<HelpCenter>,
  ): Promise<HelpCenter> {
    const entity = await this.repo.findOne({ where: { id } });
    if (!entity) throw new Error('Record not found');
    const updated = await this.repo.save(
      this.repo.create(
        HelpCenterMapper.toPersistence({
          ...HelpCenterMapper.toDomain(entity),
          ...payload,
        }),
      ),
    );
    return HelpCenterMapper.toDomain(updated);
  }

  async remove(id: HelpCenter['id']): Promise<void> {
    await this.repo.delete(id);
  }
}
